export interface PhonePrefix {
  code: string;
  country: string;
  flag: string;
}

export const DEFAULT_PREFIX = '+34';

export const PHONE_PREFIXES: PhonePrefix[] = [
  { code: '+34', country: 'España', flag: '🇪🇸' },
  { code: '+1', country: 'Estados Unidos', flag: '🇺🇸' },
  { code: '+44', country: 'Reino Unido', flag: '🇬🇧' },
  { code: '+33', country: 'Francia', flag: '🇫🇷' },
  { code: '+49', country: 'Alemania', flag: '🇩🇪' },
  { code: '+39', country: 'Italia', flag: '🇮🇹' },
  { code: '+351', country: 'Portugal', flag: '🇵🇹' },
  { code: '+31', country: 'Países Bajos', flag: '🇳🇱' },
  { code: '+32', country: 'Bélgica', flag: '🇧🇪' },
  { code: '+41', country: 'Suiza', flag: '🇨🇭' },
  { code: '+43', country: 'Austria', flag: '🇦🇹' },
  { code: '+45', country: 'Dinamarca', flag: '🇩🇰' },
  { code: '+46', country: 'Suecia', flag: '🇸🇪' },
  { code: '+47', country: 'Noruega', flag: '🇳🇴' },
  { code: '+48', country: 'Polonia', flag: '🇵🇱' },
  { code: '+30', country: 'Grecia', flag: '🇬🇷' },
  { code: '+353', country: 'Irlanda', flag: '🇮🇪' },
  { code: '+420', country: 'República Checa', flag: '🇨🇿' },
  { code: '+421', country: 'Eslovaquia', flag: '🇸🇰' },
  { code: '+36', country: 'Hungría', flag: '🇭🇺' },
  { code: '+40', country: 'Rumania', flag: '🇷🇴' },
  { code: '+359', country: 'Bulgaria', flag: '🇧🇬' },
  { code: '+385', country: 'Croacia', flag: '🇭🇷' },
  { code: '+386', country: 'Eslovenia', flag: '🇸🇮' },
  { code: '+370', country: 'Lituania', flag: '🇱🇹' },
  { code: '+371', country: 'Letonia', flag: '🇱🇻' },
  { code: '+372', country: 'Estonia', flag: '🇪🇪' },
  { code: '+358', country: 'Finlandia', flag: '🇫🇮' },
  { code: '+354', country: 'Islandia', flag: '🇮🇸' },
  { code: '+352', country: 'Luxemburgo', flag: '🇱🇺' },
  { code: '+377', country: 'Mónaco', flag: '🇲🇨' },
  { code: '+376', country: 'Andorra', flag: '🇦🇩' },
  { code: '+378', country: 'San Marino', flag: '🇸🇲' },
  { code: '+379', country: 'Vaticano', flag: '🇻🇦' },
  { code: '+380', country: 'Ucrania', flag: '🇺🇦' },
  { code: '+7', country: 'Rusia', flag: '🇷🇺' },
  { code: '+90', country: 'Turquía', flag: '🇹🇷' },
  { code: '+20', country: 'Egipto', flag: '🇪🇬' },
  { code: '+27', country: 'Sudáfrica', flag: '🇿🇦' },
  { code: '+212', country: 'Marruecos', flag: '🇲🇦' },
  { code: '+213', country: 'Argelia', flag: '🇩🇿' },
  { code: '+216', country: 'Túnez', flag: '🇹🇳' },
  { code: '+218', country: 'Libia', flag: '🇱🇾' },
  { code: '+220', country: 'Gambia', flag: '🇬🇲' },
  { code: '+221', country: 'Senegal', flag: '🇸🇳' },
  { code: '+222', country: 'Mauritania', flag: '🇲🇷' },
  { code: '+223', country: 'Malí', flag: '🇲🇱' },
  { code: '+224', country: 'Guinea', flag: '🇬🇳' },
  { code: '+225', country: 'Costa de Marfil', flag: '🇨🇮' },
  { code: '+226', country: 'Burkina Faso', flag: '🇧🇫' },
  { code: '+227', country: 'Níger', flag: '🇳🇪' },
  { code: '+228', country: 'Togo', flag: '🇹🇬' },
  { code: '+229', country: 'Benín', flag: '🇧🇯' },
  { code: '+230', country: 'Mauricio', flag: '🇲🇺' },
  { code: '+231', country: 'Liberia', flag: '🇱🇷' },
  { code: '+232', country: 'Sierra Leona', flag: '🇸🇱' },
  { code: '+233', country: 'Ghana', flag: '🇬🇭' },
  { code: '+234', country: 'Nigeria', flag: '🇳🇬' },
  { code: '+235', country: 'Chad', flag: '🇹🇩' },
  { code: '+236', country: 'República Centroafricana', flag: '🇨🇫' },
  { code: '+237', country: 'Camerún', flag: '🇨🇲' },
  { code: '+238', country: 'Cabo Verde', flag: '🇨🇻' },
  { code: '+239', country: 'Santo Tomé y Príncipe', flag: '🇸🇹' },
  { code: '+240', country: 'Guinea Ecuatorial', flag: '🇬🇶' },
  { code: '+241', country: 'Gabón', flag: '🇬🇦' },
  { code: '+242', country: 'República del Congo', flag: '🇨🇬' },
  { code: '+243', country: 'República Democrática del Congo', flag: '🇨🇩' },
  { code: '+244', country: 'Angola', flag: '🇦🇴' },
  { code: '+245', country: 'Guinea-Bisáu', flag: '🇬🇼' },
  { code: '+246', country: 'Diego García', flag: '🇮🇴' },
  { code: '+248', country: 'Seychelles', flag: '🇸🇨' },
  { code: '+249', country: 'Sudán', flag: '🇸🇩' },
  { code: '+250', country: 'Ruanda', flag: '🇷🇼' },
  { code: '+251', country: 'Etiopía', flag: '🇪🇹' },
  { code: '+252', country: 'Somalia', flag: '🇸🇴' },
  { code: '+253', country: 'Yibuti', flag: '🇩🇯' },
  { code: '+254', country: 'Kenia', flag: '🇰🇪' },
  { code: '+255', country: 'Tanzania', flag: '🇹🇿' },
  { code: '+256', country: 'Uganda', flag: '🇺🇬' },
  { code: '+257', country: 'Burundi', flag: '🇧🇮' },
  { code: '+258', country: 'Mozambique', flag: '🇲🇿' },
  { code: '+260', country: 'Zambia', flag: '🇿🇲' },
  { code: '+261', country: 'Madagascar', flag: '🇲🇬' },
  { code: '+262', country: 'Reunión', flag: '🇷🇪' },
  { code: '+263', country: 'Zimbabue', flag: '🇿🇼' },
  { code: '+264', country: 'Namibia', flag: '🇳🇦' },
  { code: '+265', country: 'Malaui', flag: '🇲🇼' },
  { code: '+266', country: 'Lesoto', flag: '🇱🇸' },
  { code: '+267', country: 'Botsuana', flag: '🇧🇼' },
  { code: '+268', country: 'Esuatini', flag: '🇸🇿' },
  { code: '+269', country: 'Comoras', flag: '🇰🇲' },
  { code: '+52', country: 'México', flag: '🇲🇽' },
  { code: '+54', country: 'Argentina', flag: '🇦🇷' },
  { code: '+55', country: 'Brasil', flag: '🇧🇷' },
  { code: '+56', country: 'Chile', flag: '🇨🇱' },
  { code: '+57', country: 'Colombia', flag: '🇨🇴' },
  { code: '+58', country: 'Venezuela', flag: '🇻🇪' },
  { code: '+51', country: 'Perú', flag: '🇵🇪' },
  { code: '+53', country: 'Cuba', flag: '🇨🇺' },
  { code: '+591', country: 'Bolivia', flag: '🇧🇴' },
  { code: '+592', country: 'Guyana', flag: '🇬🇾' },
  { code: '+593', country: 'Ecuador', flag: '🇪🇨' },
  { code: '+594', country: 'Guayana Francesa', flag: '🇬🇫' },
  { code: '+595', country: 'Paraguay', flag: '🇵🇾' },
  { code: '+596', country: 'Martinica', flag: '🇲🇶' },
  { code: '+597', country: 'Surinam', flag: '🇸🇷' },
  { code: '+598', country: 'Uruguay', flag: '🇺🇾' },
  { code: '+599', country: 'Antillas Neerlandesas', flag: '🇧🇶' },
  { code: '+502', country: 'Guatemala', flag: '🇬🇹' },
  { code: '+503', country: 'El Salvador', flag: '🇸🇻' },
  { code: '+504', country: 'Honduras', flag: '🇭🇳' },
  { code: '+505', country: 'Nicaragua', flag: '🇳🇮' },
  { code: '+506', country: 'Costa Rica', flag: '🇨🇷' },
  { code: '+507', country: 'Panamá', flag: '🇵🇦' },
  { code: '+508', country: 'San Pedro y Miquelón', flag: '🇵🇲' },
  { code: '+509', country: 'Haití', flag: '🇭🇹' },
  { code: '+590', country: 'Guadalupe', flag: '🇬🇵' },
  { code: '+1-246', country: 'Barbados', flag: '🇧🇧' },
  { code: '+1-264', country: 'Anguila', flag: '🇦🇮' },
  { code: '+1-268', country: 'Antigua y Barbuda', flag: '🇦🇬' },
  { code: '+1-284', country: 'Islas Vírgenes Británicas', flag: '🇻🇬' },
  { code: '+1-340', country: 'Islas Vírgenes de EE.UU.', flag: '🇻🇮' },
  { code: '+1-345', country: 'Islas Caimán', flag: '🇰🇾' },
  { code: '+1-441', country: 'Bermudas', flag: '🇧🇲' },
  { code: '+1-473', country: 'Granada', flag: '🇬🇩' },
  { code: '+1-649', country: 'Islas Turcas y Caicos', flag: '🇹🇨' },
  { code: '+1-664', country: 'Montserrat', flag: '🇲🇸' },
  { code: '+1-670', country: 'Islas Marianas del Norte', flag: '🇲🇵' },
  { code: '+1-671', country: 'Guam', flag: '🇬🇺' },
  { code: '+1-684', country: 'Samoa Americana', flag: '🇦🇸' },
  { code: '+1-721', country: 'San Martín', flag: '🇸🇽' },
  { code: '+1-758', country: 'Santa Lucía', flag: '🇱🇨' },
  { code: '+1-767', country: 'Dominica', flag: '🇩🇲' },
  { code: '+1-784', country: 'San Vicente y las Granadinas', flag: '🇻🇨' },
  { code: '+1-787', country: 'Puerto Rico', flag: '🇵🇷' },
  { code: '+1-809', country: 'República Dominicana', flag: '🇩🇴' },
  { code: '+1-868', country: 'Trinidad y Tobago', flag: '🇹🇹' },
  { code: '+1-869', country: 'San Cristóbal y Nieves', flag: '🇰🇳' },
  { code: '+1-876', country: 'Jamaica', flag: '🇯🇲' },
  { code: '+86', country: 'China', flag: '🇨🇳' },
  { code: '+81', country: 'Japón', flag: '🇯🇵' },
  { code: '+82', country: 'Corea del Sur', flag: '🇰🇷' },
  { code: '+91', country: 'India', flag: '🇮🇳' },
  { code: '+92', country: 'Pakistán', flag: '🇵🇰' },
  { code: '+93', country: 'Afganistán', flag: '🇦🇫' },
  { code: '+94', country: 'Sri Lanka', flag: '🇱🇰' },
  { code: '+95', country: 'Myanmar', flag: '🇲🇲' },
  { code: '+98', country: 'Irán', flag: '🇮🇷' },
  { code: '+60', country: 'Malasia', flag: '🇲🇾' },
  { code: '+61', country: 'Australia', flag: '🇦🇺' },
  { code: '+62', country: 'Indonesia', flag: '🇮🇩' },
  { code: '+63', country: 'Filipinas', flag: '🇵🇭' },
  { code: '+64', country: 'Nueva Zelanda', flag: '🇳🇿' },
  { code: '+65', country: 'Singapur', flag: '🇸🇬' },
  { code: '+66', country: 'Tailandia', flag: '🇹🇭' },
  { code: '+84', country: 'Vietnam', flag: '🇻🇳' },
  { code: '+850', country: 'Corea del Norte', flag: '🇰🇵' },
  { code: '+852', country: 'Hong Kong', flag: '🇭🇰' },
  { code: '+853', country: 'Macao', flag: '🇲🇴' },
  { code: '+855', country: 'Camboya', flag: '🇰🇭' },
  { code: '+856', country: 'Laos', flag: '🇱🇦' },
  { code: '+880', country: 'Bangladés', flag: '🇧🇩' },
  { code: '+886', country: 'Taiwán', flag: '🇹🇼' },
  { code: '+960', country: 'Maldivas', flag: '🇲🇻' },
  { code: '+961', country: 'Líbano', flag: '🇱🇧' },
  { code: '+962', country: 'Jordania', flag: '🇯🇴' },
  { code: '+963', country: 'Siria', flag: '🇸🇾' },
  { code: '+964', country: 'Irak', flag: '🇮🇶' },
  { code: '+965', country: 'Kuwait', flag: '🇰🇼' },
  { code: '+966', country: 'Arabia Saudita', flag: '🇸🇦' },
  { code: '+967', country: 'Yemen', flag: '🇾🇪' },
  { code: '+968', country: 'Omán', flag: '🇴🇲' },
  { code: '+970', country: 'Palestina', flag: '🇵🇸' },
  { code: '+971', country: 'Emiratos Árabes Unidos', flag: '🇦🇪' },
  { code: '+972', country: 'Israel', flag: '🇮🇱' },
  { code: '+973', country: 'Baréin', flag: '🇧🇭' },
  { code: '+974', country: 'Catar', flag: '🇶🇦' },
  { code: '+975', country: 'Bután', flag: '🇧🇹' },
  { code: '+976', country: 'Mongolia', flag: '🇲🇳' },
  { code: '+977', country: 'Nepal', flag: '🇳🇵' },
  { code: '+992', country: 'Tayikistán', flag: '🇹🇯' },
  { code: '+993', country: 'Turkmenistán', flag: '🇹🇲' },
  { code: '+994', country: 'Azerbaiyán', flag: '🇦🇿' },
  { code: '+995', country: 'Georgia', flag: '🇬🇪' },
  { code: '+996', country: 'Kirguistán', flag: '🇰🇬' },
  { code: '+998', country: 'Uzbekistán', flag: '🇺🇿' },
];
